<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\.build\Be.Vlaanderen.Basisregisters.Build.Pipeline\Content\Be.Vlaanderen.Basisregisters.Build.Pipeline.Settings.Library.props" />

  <PropertyGroup>
    <Version>1.0.0</Version>
    <PackageId>Be.Vlaanderen.Basisregisters.AspNetCore.Mvc.Middleware.DefaultResponseCompressionQuality</PackageId>
    <Title>Be.Vlaanderen.Basisregisters.AspNetCore.Mvc.Middleware.DefaultResponseCompressionQuality</Title>
    <Authors>Basisregisters Vlaanderen</Authors>
    <Owners>Digitaal Vlaanderen</Owners>
    <Copyright>Copyright (c) Digitaal Vlaanderen</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <PackageProjectUrl>https://github.com/Informatievlaanderen/default-response-compression-quality-middleware</PackageProjectUrl>
    <PackageIcon>logo.png</PackageIcon>
    <Description>ASP.NET Core MVC Middleware to define default compression quality priorities.</Description>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\.build\Be.Vlaanderen.Basisregisters.Build.Pipeline\Content\logo.png" Pack="true" PackagePath="" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SourceLink.Embed.AllSourceFiles" PrivateAssets="all" />
    <PackageReference Include="SourceLink.Copy.PdbFiles" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
</Project>
